name: Ember
options:
  bundleIdPrefix: com.incendoai
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: Ember/Info.plist
    GENERATE_INFOPLIST_FILE: false
packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"
  HighlightSwift:
    url: https://github.com/appstefan/HighlightSwift
    from: "1.0.0"
  Vortex:
    url: https://github.com/twostraws/Vortex
    from: "1.0.0"
targets:
  Ember:
    type: application
    platform: iOS
    sources: [Ember]
    dependencies:
      - package: MarkdownUI
      - package: HighlightSwift
      - package: Vortex
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.incendoai.ember
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  EmberTests:
    type: bundle.unit-test
    platform: iOS
    sources: [EmberTests]
    dependencies:
      - target: Ember
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.incendoai.ember.tests
  EmberUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [EmberUITests]
    dependencies:
      - target: Ember
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.incendoai.ember.uitests
