import Foundation

// MARK: - Briefing

/// A daily morning briefing summary generated by the Gateway.
struct Briefing: Identifiable, Codable, Equatable {
    let id: String
    let title: String
    let summary: String
    let date: Date
    let actionItems: [String]
    let sourceMessages: [String]
    let messageCount: Int
    let urgentCount: Int

    init(
        id: String = UUID().uuidString,
        title: String,
        summary: String,
        date: Date = Date(),
        actionItems: [String] = [],
        sourceMessages: [String] = [],
        messageCount: Int = 0,
        urgentCount: Int = 0
    ) {
        self.id = id
        self.title = title
        self.summary = summary
        self.date = date
        self.actionItems = actionItems
        self.sourceMessages = sourceMessages
        self.messageCount = messageCount
        self.urgentCount = urgentCount
    }
}
